### ISSUE TITLE
Setting listen_address fails on CentOS 7.2

### ISSUE THREAD

**Issue by alappe** [sous-chefs/varnish#103]
Normally I used `normal['varnish']['listen_address'] = '127.0.0.1'`. This doesn't have any effect on CentOS 7.2, `/etc/varnish/varnish.params` is not updated. I then tried

``` ruby
  7 varnish_default_config 'default' do
  8   listen_address '127.0.0.1'
  9 end
```

which results in

```
Chef::Exceptions::ValidationFailed
Option listen_address must be a kind of [Fixnum]!  You passed "127.0.0.1".
```

but `listen_address` is documented to take a string…

What am I missing here?

**Comment by martinb3** [comment]
HI @alappe -- there's two implementations in this cookbook; one is strictly the recipe, and the other is a resource. They're totally independent, and the original maintainers were planning on moving the recipe to use the resource. But that hasn't happened. It sounds like this may just be a bug. What version of Chef and this cookbook are you using?

**Comment by alappe** [comment]
Chef: `12.8.1`
Cookbook: `2.3.0`

I've seen #95 and using the resource variant was only to see if that might work. My main issue is that the config variant doesn't write `/etc/varnish/varnish.params` so I cannot bind varnish on `127.0.0.1` in CentOS 7.2

**Comment by KevinMace** [comment]
@alappe Did you find a solution to `/etc/varnish/varnish.params` not being configurable? Only i'm having the same issue when trying to set the listen_port and the documentation doesn't yield any clues.

**Comment by RyanJarv** [comment]
This cookbook doesn't use `/etc/varnish/varnish.params` on systemd currently, it manages and sets the address property directly in the systemd configuration file at `/etc/sysconfig/varnish`. I agree leaving varnish.params around is confusing though.

If this is still an issue in version 3.x can you check what is being set in `/etc/sysconfig/varnish`?

It's worth noting the attribute for configuring it in via the recipe in 3.x the attribute has changed to `node['varnish']['configure']['config']['listen_address']` (https://github.com/rackspace-cookbooks/varnish#recipe-examples). For the varnish_config resource (replaced_varnish_default_config) the property is still listen_address (https://github.com/rackspace-cookbooks/varnish#resource-recipe-example).

**Comment by RyanJarv** [comment]
Going to close this ticket, let us know if you are still having any issues setting the listen_address.
