### ISSUE TITLE
Varnishncsa reload not working and logrotate failing to rotate logs

### ISSUE THREAD

**Issue by anabadce** [sous-chefs/varnish#134]
### Cookbook version
3.1.0

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04.2 LTS 64-bit

### Scenario:
Rotation of the *varnishncsa.log* file doesn't work because service *varnishncsa* is not reloaded.

### Steps to Reproduce:
1. Install Varnish and configure Varnishncsa logging:

```
include_recipe "varnish"

varnish_repo 'varnish' do
  major_version 4.1
end

package 'varnish'

varnish_log 'default_ncsa' do
  file_name '/var/log/varnish/varnishncsa.log'
  pid '/var/run/varnishncsa.pid'
  log_format 'varnishncsa'
end
```

2. See content of `/etc/logrotate.d/varnish` and try reloading Varnishncsa
It uses this to reload varnishncsa after rotating the log file:
```
/usr/sbin/invoke-rc.d varnishncsa reload > /dev/null
```

3. Notice this command won't work as reload is not supported
```
ubuntu@varnishdev:~$ systemctl show varnishncsa | grep Reload
CanReload=no
```

### Expected Result:
Varnishncsa should reload

### Actual Result:
Varnishncsa doesn't reload causing the rotation of log files to not work properly (among other possible issues)

### Suggestion for fix:
Problem is file `/etc/systemd/system/varnishncsa.service` is replaced by Chef with a new file made from this template:
[`varnishlog_systemd.erb`](/sous-chefs/varnish/blob/master/templates/default/varnishlog_systemd.erb)

This file is different from the file that comes from the package and it is missing some configuration lines, the *ExecReload* for example, compare it with the original `varnishncsa.service` file:
```
[Unit]
Description=Varnish Cache HTTP accelerator NCSA logging daemon
After=varnish.service

[Service]
RuntimeDirectory=varnishncsa
Type=forking
PIDFile=/run/varnishncsa/varnishncsa.pid
User=varnishlog
Group=varnish
ExecStart=/usr/bin/varnishncsa -a -w /var/log/varnish/varnishncsa.log -D -P /run/varnishncsa/varnishncsa.pid
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

So updating the template in the recipe should fix this problem.

**Comment by RyanJarv** [comment]
Thanks for the detailed report!

If you have a branch that is working for you currently a pull request would be awesome. However if not I was able to reproduce this and will try to test your fix later this week sometime.
Also not sure if it will help at all but it looks like running the init.d script directly works as a work around for now as well.
