### ISSUE TITLE
ncsa_format_string needs "%" escaped for systemd

### ISSUE THREAD

**Issue by sbuzonas** [sous-chefs/varnish#137]
### Cookbook version
master

### Chef-client version
13.2.20

### Platform Details
Ubuntu 16

### Scenario:
Enable the logging service with the `varnishncsa` format.

### Steps to Reproduce:
Set `default['varnish']['configure']['ncsa']['action'] = :configure` and install on a systemd platform.

### Expected Result:
```
192.168.32.1|-|-|[09/Jul/2017:13:34:42 +0000]|"GET http://mysite.local/ HTTP/1.1"|200|52109|"-"|"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
```

### Actual Result:
```
/|-|root|/run|"/system.slice"|/bin/sh|f46fb581373b43fd9ed9374f3e3091d3|"http://mysite.local/"|"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
```

**Comment by RyanJarv** [comment]
Just for fun linking to another issue with the log output that I fixed somewhat recently. Seems like this is hard to get right.

https://github.com/sous-chefs/varnish/pull/127

**Comment by sbuzonas** [comment]
I have a fix, I was opening this to make a PR against and completely forgot about it. I'll try to find it and put a PR together.

If I don't get around to it before somebody needs a fix... I injected a simple helper to the template in the log resource that does `gsub('%', '%%')` and called the helper method in the systemd template...

**Comment by RyanJarv** [comment]
Awesome a PR would be awesome if you have it. I was thinking I would have time to dig into this some more but haven't got around to it yet.
