### ISSUE TITLE
Update varnish repo

### ISSUE THREAD

**Issue by RyanJarv** [sous-chefs/varnish#140]
This is from the varnish mailing list. This is also a blocker for supporting 5+ on certain platforms I believe.

```
Hi,

The old repository-setup at http://repo.varnish-cache.org/ is being shut down
on the 31st of August.

For a while, the official project package repositories have been hosted at
https://packagecloud.io/varnishcache/.
Now, we are removing the old apt/yum repository servers.

If you are currently using the old repositories with yum/apt, please take
steps to move your hosts to use the new repos.

Instructions for configuration of the current repositories can be found on
our website:
http://www.varnish-cache.org/releases/install_debian.html
http://www.varnish-cache.org/releases/install_redhat.html

The source .tar.gz files will be served through the main website.
See the complete list of releases at http://varnish-cache.org/releases/
for download links.

Regards
-- 
Denis Brækhus Senior Engineer | Varnish Software AS 
Cell: +47 48047724
We Make Websites Fly!
www.varnish-software.com 

_______________________________________________
varnish-announce mailing list
varnish-announce@varnish-cache.org
https://www.varnish-cache.org/lists/mailman/listinfo/varnish-announce
```

**Comment by RyanJarv** [comment]
Just a reminder this is coming up shortly. I'll try to get this done if possible but pretty tight on time right now.

**Comment by wbotelhos** [comment]
@RyanJarv Any prevision when you will support Varnish 5.1?

The new binary URL should be `http://repo.varnish-cache.org/source/varnish-${version}.tar.gz`

I appreciate your support and thank you for your great work. :)

**Comment by RyanJarv** [comment]
Thanks! Sorry, I do not know when we'll be able to get 5.1 supported. Although with #141 merged in now it may be as simple as updating the version in a few places (like https://github.com/sous-chefs/varnish/blob/master/resources/varnish_repo_debian.rb#L5, etc..).

If you have time PR's are always appreciated!
