### ISSUE TITLE
No GPG key used on RHEL

### ISSUE THREAD

**Issue by RyanJarv** [sous-chefs/varnish#145]
### Cookbook version
Master

### Scenario:
No GPG key used on RHEL. Before this was because there was no GPG key provided for the upstream varnish repo. I believe this is fixed with the move to packagecloud and we should be checking for this.

https://github.com/sous-chefs/varnish/blob/87702a3c5adfdcc40b42d6777655f1af1ef20cdb/resources/varnish_repo_redhat.rb#L13

**Comment by gsreynolds** [comment]
I cribbed from the [packagecloud installation scripts](https://packagecloud.io/varnishcache/varnish41/install) for #141. rpm installation script outputs the following which disables gpgcheck, but enables repo_gpgcheck instead.

https://packagecloud.io/install/repositories/varnishcache/varnish41/config_file.repo?os=el&dist=7&source=script
```
[varnishcache_varnish41]
name=varnishcache_varnish41
baseurl=https://packagecloud.io/varnishcache/varnish41/el/7/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/varnishcache/varnish41/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

**Comment by RyanJarv** [comment]
Ah ok didn't notice that, made a PR for the repo_gpgcheck attribute but will leave this ticket open until we can enable gpgcheck.
