### ISSUE TITLE
Varnish Repositories Need to Be Updated to packagecloud.io

### ISSUE THREAD

**Issue by thatElectricFeel** [sous-chefs/varnish#146]
### Cookbook version
3.3.0

### Chef-client version
12.11.18

### Platform Details
Ubuntu 14.04

### Scenario:
Install Varnish

### Steps to Reproduce:
Run sudo chef-client -o varnish

### Expected Result:
Varnish installed

### Actual Result:
Varnish is not installed, get error that service does not exist.

Updating varnish\recipes\repo.rb to use http://packagecloud.io/varnishcache/ instead of http://repo.varnish-cache.org fixes the problem.

**Comment by RyanJarv** [comment]
Hey, thanks for the issue report!

Can you check that you are using version 3.3.0? That version was released this morning to fix this issue. Here's a link to that PR: https://github.com/sous-chefs/varnish/pull/141

**Comment by gsreynolds** [comment]
Yep, are you sure you are using 3.3.0, there is no recipes/repo.rb file in the cookbook: https://github.com/sous-chefs/varnish/tree/master/recipes

**Comment by thatElectricFeel** [comment]
My metadata.json says 3.3.0, but I will clear and reinstall.

Regards,

*Christina M. Gleason*Software Engineer

Office: (413) 679-1033
Cell: (203) 528-5893
Email: christinamgleason@gmail.com

**Comment by thatElectricFeel** [comment]
Fresh install did it - thank you!
