### ISSUE TITLE
Not able to change the value for "file_storage_size", defaulting to 1002246K 

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/varnish#194]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description
I am using the following resource to set the values for respective parameters.  

```ruby
varnish_config 'config' do
  start_on_boot true
  listen_port 80
  storage 'malloc'
  file_storage_size '5GB'
  ttl 0
end
```

Expected the STORAGE parameter in Varnish config hold 5GB, instead it set to the default value 1GB. 

_STORAGE=malloc,1002246K_

## :pancakes: Cookbook version

CookBook Version 4.0.1
Varnish version 3.0.7

## :woman_cook:  Chef-Infra Version

14.10.9

## :tophat: Platform details

CentOS 6.9.0

**Comment by damacus** [comment]
I'm guessing here (because I haven't worked on this cookbook in a while) that there's a parameter missing to allow that setting. Or you just need to set `storage` to, `storage = 'mallock, 1002246K'`

**Comment by gangadhar01a** [comment]
Thanks @damacus , I have tried changing the storage parameter which has not fixed the issue as the parameter expecting either "malloc or file" 
 

"FATAL: Chef::Exceptions::ValidationFailed: Option storage must be equal to one of: "file", "malloc"!  You passed "malloc, 200246K"."

**Comment by gangadhar01a** [comment]
Hi @damacus , just went through the code and understood in order to change the size I have to use the "malloc_size" parameter when we have selected the storage as "malloc". 

storage = [@config.storage, @malloc_size].compact.join(",")
