### ISSUE TITLE
RELOAD_VCL only set for systemd

### ISSUE THREAD

**Issue by jhmartin** [sous-chefs/varnish#76]
https://github.com/rackspace-cookbooks/varnish/blob/master/templates/default/lib_default_systemd.erb sets RELOAD_VCL = 1, while this line is entirely omitted from the init.d-based version.

This should be included in both versions and made configurable.

**Comment by martinb3** [comment]
Perhaps we should switch to the packaged init scripts as I asked in #75 as well?
